#!/bin/bash
####################################################################
#
#  Preprocesses a librcd c input file.
#
#  SYNOPSIS:
#      ./rcd-pp [clang pre-processor arguments] > outfile.i
#
#  Copyright © 2014, Jumpstarter AB. This file is part of the librcd project.
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at http://mozilla.org/MPL/2.0/.
#  See the COPYING file distributed with this project for more information.
#
####################################################################

set -e
set -o pipefail

clang -nostdlib -nostdinc -std=gnu11 $@ | rcd-post-pp
